trigger: none

pool:
  vmImage: windows-latest

parameters:
- name: SourceVirtualWanHubResourceId
  displayName: Source Virtual WanHubResource ID
  type: string
- name: SourceConnectionName
  displayName: Source Peering Connection Name
  type: string
- name: DestinationVirtualWanHubResourceId
  displayName: Destination Virtual WanHubResource ID
  type: string
- name: RemoteVirtualNetworkResourceId
  displayName: Remote Virtual NetworkResource Id
  type: string


variables:
  ServiceConnectionName: "nx-devops-mgmt"
  ManagementGroupPrefix: "nx"
  HubNetworkSubId: "1e35dc95-64a6-48a0-a5ff-8cd94542c990"
  RunNumber: $(Build.BuildNumber)

stages:

- stage: DisconnectFromCorp
  jobs:
  - job:
    steps:
    - checkout: self
      displayName: Checkout Repo

    - script: |
        echo 'Disconnecting from Corp'

    - task: AzurePowerShell@5
      inputs:
        azureSubscription: '$(ServiceConnectionName)'
        ScriptType: 'FilePath'
        ScriptPath: './src/Remove-HubVnetConnection.ps1'
        ScriptArguments: '-VirtualWanHubResourceId "${{ parameters.SourceVirtualWanHubResourceId }}" -ConnectionName "${{ parameters.SourceConnectionName }}"'
        azurePowerShellVersion: 'LatestVersion'

- stage: Connect2BU

  jobs:
  - job:
  
    steps:
    - checkout: self
      displayName: Checkout Repo

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Subscription'
        azureResourceManagerConnection: 'nx-devops-mgmt'
        subscriptionId: $(HubNetworkSubId)
        location: 'East US 2'
        templateLocation: 'Linked artifact'
        csmFile: 'src/main.bicep'
        deploymentMode: 'Incremental'
        overrideParameters: >
          -parVirtualWanHubResourceId ${{ parameters.DestinationVirtualWanHubResourceId }}
          -parRemoteVirtualNetworkResourceId ${{ parameters.RemoteVirtualNetworkResourceId }}

- stage: OptionalRollback2Corp
  jobs:
  - job:
    pool: server 
    steps:

    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          realjonathanryan@ymail.com
          realjonathanryan@gmail.com
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'

  - job:
    steps:
    - script: |
        echo 'Rollback'
